algoritmo "EXERCICIO_01-c"
// Função : Calcular a média de quatro números inteiros lidos
// Autor :
// Data : 18/08/2015
// Seção de Declarações
var N1, N2, N3, N4: Inteiro

inicio
// Seção de Comandos
Escreva("Digite 1o numero: ")
Leia (N1)
Escreva("Digite 2o numero: ")
Leia (N2)
Escreva("Digite 3o numero: ")
Leia (N3)
Escreva("Digite 4o numero: ")
Leia (N4)
Escreva ("A media aritimetica dos quatros numeros e: ", (N1 + N2 + N3 + N4) / 4)
fimalgoritmo
