site_name: Algoritimos e Lógica de Programação
site_description: Lista de exercícios da disciplina de Algoritimos e Lógica de Programação do curso de Analise e Desenvolvimento de Sistemas da FATEC de Franca.
site_author: Getúlio Vinicius <getuliovinits@gmail.com>
google_analytics: ['UA-70830801-7', 'auto']
repo_url: https://github.com/getuliovinicius/algoritimos.logica.programacao
repo_name: GitHub
edit_uri: blob/master/docs/mds/
remote_branch: gh-pages
remote_name: origin
docs_dir: 'mds'
pages:
  - Inicio: index.md
theme: readthedocs
extra:
    version: 1.0
markdown_extensions:
    - smarty
    - nl2br
    - admonition
    - codehilite
    - sane_lists
    - toc:
        permalink: True
        separator: "_"
    - footnotes
